# Data Acquisition

### Case Study: MIA

First step of machine learning pipeline is data acquisition, which involves loading data from various sources into our Python enivronment.

This notebook will focus on the data obtained from [MIA](https://maltairport.com/corporate/traffic-development/statistics/)

## Importing Libraries

In [1]:
import pandas as pd
import os.path as osp

## Loading the dataset

Load the dataset from a CSV, and do not use hardcoded paths

In [4]:
path = osp.join('..','..','data','mia','miaPassengers 01.csv')

df = pd.read_csv(path)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        19 non-null     int64
 1   passengers  19 non-null     int64
dtypes: int64(2)
memory usage: 436.0 bytes

In [5]:
df.head()

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [6]:
df.tail(3)

    year  passengers
16  2021     2540335
17  2022     5851079
18  2023     7803042

In [15]:
path =  osp.join('..','..','data','mia','miaPassengers 02.csv')

df = pd.read_csv(path,sep=';')

df.head()

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [17]:
path =  osp.join('..','..','data','mia','miaPassengers.txt')

df = pd.read_csv(path,sep='\t')

df.head()

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

In [18]:
path =  osp.join('..','..','data','mia','miaPassengers.json')

df = pd.read_json(path)

df.head()

   year  passengers
0  2005     2397049
1  2006     2696034
2  2007     2974501
3  2008     3109868
4  2009     2918664

### Split Files (Data and Headers)

In [28]:
# Read headers using standard file reading

path =  osp.join('..','..','data','mia','miaPassengers.names')

with open(path,'r',encoding='utf-8-sig') as f:
    columns = f.read().strip().split(',')

path =  osp.join('..','..','data','mia','miaPassengers.data')

df = pd.read_csv(path,header=None,names=columns)

df

    year  passengers
0   2005     2397049
1   2006     2696034
2   2007     2974501
3   2008     3109868
4   2009     2918664
5   2010     3293524
6   2011     3506521
7   2012     3649938
8   2013     4031500
9   2014     4290304
10  2015     4618640
11  2016     5080071
12  2017     6014548
13  2018     6808177
14  2019     7310289
15  2020     1748050
16  2021     2540335
17  2022     5851079
18  2023     7803042